import os
Import('*')

EXE = "python"
SCRIPT = "make-tests.py"
SRC =  "CuTest/make-tests.py"
ARGS =  "-o $TARGET $SOURCES"
COMSTR = EXE + " " + SCRIPT + " " + ARGS if VERBOSE else "GEN $TARGET"

t = addPrebuiltTool(SCRIPT, SRC, ARGS, EXE, comstr=COMSTR)

test_src = Glob('miniat_*/*.c')

r = useTool('make-tests.py', 'tests.c', test_src )

NAME = 'miniat_tests'
INC = [ 'CuTest', '#/vm/inc', '#/vm/src' ]
SRC = [r, test_src, 'CuTest/CuTest.c']

x = buildProgram(NAME, SRC, CPPPATH=INC , LIBS='miniat')

buildMash('asms/bus_read.asm')
buildMash('asms/bus_write.asm')
buildMash('asms/store_load.asm')
buildMash('asms/timer_count.asm')
buildMash('asms/timer_reset.asm')
buildMash('asms/timer_time.asm')
buildMash('asms/timer_toggle.asm')
buildMash('asms/watchdog.asm')

env.Depends(r, t)
env.Depends(x, r)
